#!/usr/bin/env python3
"""A small command-line collection of computer science jokes."""

import random


JOKES = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "There are only 10 kinds of people in the world: those who understand binary and those who don't.",
    "A SQL query walks into a bar, walks up to two tables, and asks, 'Can I join you?'",
    "Why was the JavaScript developer sad? Because he didn't know how to `null` his feelings.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "I would tell you a UDP joke, but you might not get it.",
    "I would tell you a TCP joke, but I'd have to keep repeating it until you got it.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why was the computer cold? It left its Windows open.",
    "What do computers eat for a snack? Microchips.",
    "What do you call a computer that sings? A Dell.",
    "Why did the developer go broke? He used up all his cache.",
    "Why do Java developers wear glasses? Because they don't C#.",
    "What's a programmer's favorite place in the house? The cache drawer.",
    "A programmer's wife tells him: 'Go to the store and get a loaf of bread. If they have eggs, get a dozen.' He comes home with twelve loaves of bread.",
    "How many programmers does it take to change a light bulb? None. That's a hardware problem.",
    "How many programmers does it take to screw in a light bulb? Just one, but the bulb will be replaced three times because of changing requirements.",
    "Why was the recursive function late? It had to call itself before leaving.",
    "A programmer walks into a bar and orders 1.00000000000000000001 root beers. The bartender says, 'Please go home; you're drunk.'",
    "A programmer walks into a bar and orders a drink. The bartender says, 'We don't serve your type.'",
    "A programmer walks into a bar and orders a drink, two drinks, 0 drinks, 99 drinks, -1 drinks, a drink, and a null drink. The bartender asks, 'What was that?' The bar crashes.",
    "Why did the function return early? It had a commitment issue.",
    "The programmer got stuck in the shower because the instructions said: Lather, Rinse, Repeat.",
    "What's a computer's favorite beat? An algorithm.",
    "Why do programmers confuse Halloween and Christmas? Because Oct 31 == Dec 25.",
    "What did the router say to the doctor? 'It hurts when IP.'",
    "What did the web developer say to the HTML element? 'You complete me.'",
    "Why did the CSS developer break up with HTML? There was no style in the relationship.",
    "What's a pirate's favorite programming language? R.",
    "What's a pirate's favorite data structure? An arr, because it has a lot of booty.",
    "Why couldn't the server play cards? It kept dealing with too many requests.",
    "Why did the cache go to therapy? It had too many unresolved issues.",
    "Why are computers so good at tennis? They have great backhands and a powerful cache.",
    "Why did the computer get glasses? It needed to improve its web sight.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the computer cross the road? It was programmed by a chicken.",
    "Why did the computer sneeze? It had a bad case of the blue screen of death.",
    "What's a computer's favorite ocean? The Pacific, because it has no conflicts.",
    "Why did the database administrator leave his wife? She had too many relationships.",
    "Why did the database administrator break up with the table? It had too many foreign keys.",
    "Why did the developer bring a ladder to work? The project had too many high-level requirements.",
    "What is a programmer's favorite musical instrument? The keyboard.",
    "Why did the IDE go to school? It wanted to improve its classpath.",
    "Why did the software engineer bring a pencil to the meeting? To draw a line between scope and scope creep.",
    "What's the difference between a junior developer and a senior developer? A junior developer asks what the error means; a senior developer asks why it exists.",
    "A byte walks into a bar. The bartender asks, 'What's wrong?' The byte says, 'Parity error.' The bartender says, 'You look a bit off.'",
    "Bits are always getting into arguments. They just can't agree on whether it's one or zero.",
    "Why did the Boolean go to therapy? It couldn't decide how it felt.",
    "What did the stack say to the heap? 'Stop pushing my buttons.'",
    "Why did the stack break up with the queue? It couldn't handle the FIFO lifestyle.",
    "What did the linked list say when it lost its pointer? 'I'll never find myself.'",
    "Why did the binary tree get promoted? It had great branches.",
    "Why did the graph apply for a job? It had connections.",
    "Why was the algorithm so calm? It had excellent time complexity under pressure.",
    "Why did Big O go to the doctor? It was feeling asymptotically unwell.",
    "Why did the sorting algorithm get detention? It kept putting things in order.",
    "What did the quicksort say after a breakup? 'I need some space to partition.'",
    "Why is insertion sort a good dinner guest? It knows how to insert itself politely.",
    "Why did the binary search algorithm get lost? It only checked half the directions.",
    "Why did the hash table get invited to every party? It had the best collisions.",
    "Why did the compiler take a vacation? It needed to get away from all the errors.",
    "What did the compiler say to the syntax error? 'You don't parse me.'",
    "Why did the code fail the interview? It had no class.",
    "Why did the bug go to school? To become a feature.",
    "A bug is just an undocumented feature with excellent marketing.",
    "Why was the debugger a great detective? It always followed the stack trace.",
    "Why did the developer sleep under the keyboard? They wanted to catch some Zs.",
    "Why did the test case feel lonely? Nobody ever ran it.",
    "Why did the unit test get promoted? It passed every test of character.",
    "What did the QA engineer say after finding a bug? 'This is not a bug; it's a surprise feature.'",
    "Why did the code review take so long? Everyone had a point to make.",
    "Why did the Git repository go to therapy? It had too many unresolved conflicts.",
    "Why did Git get kicked out of the party? It kept committing crimes.",
    "What did the developer say after deleting the wrong branch? 'I've made a grave git mistake.'",
    "Why did the branch break up with main? It needed more space to develop.",
    "Why was the merge so emotional? It had unresolved conflicts.",
    "Why did the open-source project go to the doctor? It had a severe case of dependency issues.",
    "Why did the package manager break up with the library? It couldn't resolve their dependency.",
    "What do containers say when they are full? 'Docker? I hardly know her.'",
    "Why did the cloud break up with the server? It needed space.",
    "Why did the cloud get promoted? It was outstanding in its field.",
    "Why did the sysadmin carry an umbrella? There was a chance of cloud formation.",
    "Why did the server keep its cool? It had a good fan base.",
    "Why did the network administrator get stuck in traffic? There was a bottleneck.",
    "Why did the Wi-Fi go to couples counseling? It had connection problems.",
    "Why did the packet arrive late? It took the wrong route.",
    "What did one IP address say to the other? 'I know where you live.'",
    "Why did the firewall get promoted? It was good at setting boundaries.",
    "Why did the security engineer bring a lock to work? They wanted to secure the perimeter.",
    "Why did the password go to therapy? It was too easy to guess its feelings.",
    "What is a hacker's favorite season? Fall, because everything has vulnerabilities.",
    "Why did the cryptographer get invited to every party? They always had a good key.",
    "Why did the encryption algorithm get married? It found the right key.",
    "Why did the AI cross the road? It was trained on chicken data.",
    "Why did the neural network go to the gym? It wanted stronger weights.",
    "Why was the machine-learning model so confident? It had high self-attention.",
    "Why did the robot get a timeout? It kept having too many processes.",
    "What did the computer say after a long day? 'I need to reboot my social life.'",
    "Why did the operating system start a band? It had good shell appeal.",
    "Why did the kernel refuse dessert? It was already full of processes.",
    "Why did the process go to the beach? It needed a little more runtime.",
    "Why did the thread get a blanket? It was cold and had a race condition.",
    "Why did the multithreaded program go to couples counseling? It had too many race conditions.",
    "Why did the memory manager get fired? It couldn't let go.",
    "Why was the RAM so popular? Everyone wanted to hang out with it temporarily.",
    "Why did the hard drive break up with the SSD? It needed a faster relationship.",
    "Why did the SSD win the race? It had no moving parts slowing it down.",
    "Why did the monitor apply for a job? It wanted a better display of its talents.",
    "Why did the keyboard get promoted? It had all the right keys.",
    "Why did the mouse get lost? It couldn't find its cursor.",
    "Why did the laptop go to the doctor? Its battery was feeling drained.",
    "Why did the programmer take a nap? They needed to recharge their batteries—and their brain.",
    "Why did the software engineer become a gardener? They liked working with branches and roots.",
    "Why did the computer science student bring a map to class? The professor was teaching recursion and they wanted to know where they were.",
    "A programmer's favorite exercise is running—especially when the code is late.",
    "Why did the programmer use two monitors? One for code and one for code that proves the first code is wrong.",
    "Why did the developer refuse to use stairs? They preferred a recursive elevator.",
    "Why do programmers always mix up Christmas and Halloween? Because 31 OCT = 25 DEC.",
]


def main() -> None:
    """Print every joke in a fresh random order."""
    jokes = JOKES.copy()
    random.shuffle(jokes)

    print(f"Computer Science Joke Generator ({len(jokes)} jokes)\n")
    for number, joke in enumerate(jokes, start=1):
        print(f"{number:03}. {joke}")


if __name__ == "__main__":
    main()
